
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author night
 */
public class CuttingModeCalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CuttingModeCalculatorForm
     */
    public CuttingModeCalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vcLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        fzLabel = new javax.swing.JLabel();
        zLabel = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        vfLabel = new javax.swing.JLabel();
        vcField = new javax.swing.JTextField();
        dField = new javax.swing.JTextField();
        fzField = new javax.swing.JTextField();
        zField = new javax.swing.JTextField();
        сalculateButton = new javax.swing.JButton();
        nResultLabel = new javax.swing.JLabel();
        vfResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vcLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcLabel.setText("Швидкість різання");

        dLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dLabel.setText("Діаметр колеса");

        fzLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fzLabel.setText("Подача на зуб");

        zLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zLabel.setText("Кількість зубів");

        nLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nLabel.setText("Частота обертання");

        vfLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vfLabel.setText("Швидкість подачі");

        vcField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcFieldActionPerformed(evt);
            }
        });

        dField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        fzField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        zField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        сalculateButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        сalculateButton.setText("фокус-покус");
        сalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                сalculateButtonActionPerformed(evt);
            }
        });

        nResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        vfResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(nResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vfResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vcField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dField)
                            .addComponent(dLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fzLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fzField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(сalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vcLabel)
                    .addComponent(dLabel)
                    .addComponent(fzLabel)
                    .addComponent(zLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(vcField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fzField)
                    .addComponent(zField))
                .addGap(45, 45, 45)
                .addComponent(сalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vfResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(nResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vcFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcFieldActionPerformed
//Обробка події натискання кнопки "фокус-покус"
    private void сalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_сalculateButtonActionPerformed
try{       
    //Зчитуємо і перевіряємо значення з текстових полів
        double vc = parsePositiveInput(vcField.getText(), "Швидкість різання");
        double d=  parsePositiveInput(dField.getText() ,"Діаметр");
        double fz = parsePositiveInput(fzField.getText() , "Подача на зуб");
        int z = parsePositiveIntInput(zField.getText() , "Кількість зубів");
        //Розрахунок частоти обертання n
        double n =  (1000 * vc) / (Math.PI * d);
        //Розрахунок швидкості подачі vf 
        double vf = fz * n * z;
        //Виведення результатів
        nResultLabel.setText(String.format("%.2f", n));
        vfResultLabel.setText(String.format("%.2f" , vf));
}catch (NumberFormatException ex){
    //Повідомлення про помилку,якщо введено нечислове значення
    JOptionPane.showMessageDialog(this, "Введіть числові значення в усі поля!", "Помилка введення", JOptionPane.ERROR_MESSAGE);
} catch (IllegalArgumentException ex) {
// Повідомлення про помилку, якщо введено некоректне значення
    JOptionPane.showMessageDialog(this, ex.getMessage(), "Помилка", JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_сalculateButtonActionPerformed
// Метод для перевірки числового введення (позитивне значення)
    private double parsePositiveInput(String input , String fieldName){
        try {
            double value  = Double.parseDouble(input);
            if (value <= 0 ){
                throw new IllegalArgumentException("Поле \"" + fieldName + "\" має бути більше нуля.");
                }
            return value;
        }
        catch(NumberFormatException e){
            throw new IllegalArgumentException("Поле \"" + fieldName + "\" має бути числовим значенням.");
        }
    }
    //Метод для перевірки цілого числа (позитивне значення)
    private int parsePositiveIntInput(String input , String fieldName) {
        try{
        int value = Integer.parseInt(input);
        if(value <=0) {
            throw new IllegalArgumentException("Поле \"" + fieldName + "\" має бути більше нуля");
        }
        return value;
        }
        catch(NumberFormatException e) {
            throw new IllegalArgumentException("Поле \"" +fieldName + "\" має бути цілим числом");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuttingModeCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuttingModeCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuttingModeCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuttingModeCalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuttingModeCalculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dField;
    private javax.swing.JLabel dLabel;
    private javax.swing.JTextField fzField;
    private javax.swing.JLabel fzLabel;
    private javax.swing.JLabel nLabel;
    private javax.swing.JLabel nResultLabel;
    private javax.swing.JTextField vcField;
    private javax.swing.JLabel vcLabel;
    private javax.swing.JLabel vfLabel;
    private javax.swing.JLabel vfResultLabel;
    private javax.swing.JTextField zField;
    private javax.swing.JLabel zLabel;
    private javax.swing.JButton сalculateButton;
    // End of variables declaration//GEN-END:variables
}
